-- Production SaaS hardening for IronVault.
--
-- The UI still keeps a compact JSON workspace for backwards compatibility,
-- but the workspace is now owned by a gym tenant rather than by a browser or
-- by a client-supplied owner id. All reads/writes go through SECURITY DEFINER
-- RPCs that derive the gym from auth.uid(). Receptionists receive a filtered
-- workspace and writes are merged server-side according to their permissions.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.gyms (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 120),
  subscription_plan text not null default 'free' check (subscription_plan in ('free', 'pro')),
  subscription_status text not null default 'free'
    check (subscription_status in ('free', 'trialing', 'active', 'past_due', 'canceled', 'expired')),
  trial_ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gym_users (
  gym_id uuid not null references public.gyms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'receptionist')),
  display_name text not null default '',
  email text not null default '',
  enabled boolean not null default true,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (gym_id, user_id)
);

-- The current product supports one gym workspace per login. Keeping this
-- invariant removes ambiguous tenant selection and can be relaxed later when a
-- deliberate multi-location switcher is introduced.
create unique index if not exists gym_users_one_gym_per_user_idx
  on public.gym_users (user_id);
create index if not exists gym_users_gym_role_idx on public.gym_users (gym_id, role);

alter table public.gym_workspaces add column if not exists gym_id uuid references public.gyms(id) on delete cascade;
alter table public.gym_workspaces add column if not exists revision bigint not null default 1;

-- Backfill every legacy owner workspace into a real tenant.
insert into public.gyms (owner_user_id, name)
select
  workspace.owner_id,
  coalesce(nullif(trim(workspace.state -> 'settings' ->> 'gymName'), ''), 'My Gym')
from public.gym_workspaces workspace
on conflict (owner_user_id) do nothing;

insert into public.gym_users (gym_id, user_id, role, display_name, email, enabled, permissions)
select
  gym.id,
  gym.owner_user_id,
  'owner',
  coalesce(nullif(trim(workspace.state -> 'settings' ->> 'adminName'), ''), 'Gym Owner'),
  coalesce(nullif(trim(workspace.state -> 'settings' ->> 'email'), ''), ''),
  true,
  '{}'::jsonb
from public.gyms gym
join public.gym_workspaces workspace on workspace.owner_id = gym.owner_user_id
on conflict (gym_id, user_id) do update set
  role = 'owner',
  enabled = true,
  updated_at = now();

update public.gym_workspaces workspace
set gym_id = gym.id
from public.gyms gym
where workspace.gym_id is null
  and gym.owner_user_id = workspace.owner_id;

alter table public.gym_workspaces alter column gym_id set not null;
create unique index if not exists gym_workspaces_gym_id_idx on public.gym_workspaces (gym_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  gym_id uuid not null references public.gyms(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  role text not null check (role in ('owner', 'receptionist', 'system')),
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_gym_created_idx on public.audit_logs (gym_id, created_at desc);
create index if not exists audit_logs_gym_action_idx on public.audit_logs (gym_id, action, created_at desc);

-- Durable rate-limit counters used by trusted server routes. Normal app users
-- cannot read or manipulate these counters.
create table if not exists public.api_rate_limits (
  scope text not null,
  subject text not null,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (scope, subject)
);

alter table public.gyms enable row level security;
alter table public.gym_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.api_rate_limits enable row level security;

create or replace function public.iv_current_gym_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select membership.gym_id
  from public.gym_users membership
  where membership.user_id = auth.uid()
    and membership.enabled
  order by case membership.role when 'owner' then 0 else 1 end
  limit 1
$$;

create or replace function public.iv_is_current_gym_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.gym_users membership
    where membership.user_id = auth.uid()
      and membership.gym_id = public.iv_current_gym_id()
      and membership.role = 'owner'
      and membership.enabled
  )
$$;

create or replace function public.iv_has_permission(p_permissions jsonb, p_key text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce((p_permissions ->> p_key)::boolean, false)
$$;

drop policy if exists "Members can read their gym" on public.gyms;
create policy "Members can read their gym"
  on public.gyms for select to authenticated
  using (id = public.iv_current_gym_id());

drop policy if exists "Owners can update their gym" on public.gyms;
create policy "Owners can update their gym"
  on public.gyms for update to authenticated
  using (id = public.iv_current_gym_id() and public.iv_is_current_gym_owner())
  with check (id = public.iv_current_gym_id() and public.iv_is_current_gym_owner());

drop policy if exists "Members can read permitted staff records" on public.gym_users;
create policy "Members can read permitted staff records"
  on public.gym_users for select to authenticated
  using (
    user_id = auth.uid()
    or (gym_id = public.iv_current_gym_id() and public.iv_is_current_gym_owner())
  );

drop policy if exists "Owners can read audit logs" on public.audit_logs;
create policy "Owners can read audit logs"
  on public.audit_logs for select to authenticated
  using (gym_id = public.iv_current_gym_id() and public.iv_is_current_gym_owner());

-- Client code must not access the raw JSON workspace. In particular, a
-- receptionist with product access but without cost permission must never be
-- able to reveal costs by bypassing the UI and querying PostgREST directly.
drop policy if exists "Owners can read their gym workspace" on public.gym_workspaces;
drop policy if exists "Owners can create their gym workspace" on public.gym_workspaces;
drop policy if exists "Owners can update their gym workspace" on public.gym_workspaces;
drop policy if exists "Owners can delete their gym workspace" on public.gym_workspaces;
revoke all on public.gym_workspaces from anon, authenticated;
revoke all on public.api_rate_limits from anon, authenticated;

create or replace function public.iv_validate_workspace(p_state jsonb)
returns void
language plpgsql
immutable
set search_path = public
as $$
declare
  v_key text;
begin
  if p_state is null or jsonb_typeof(p_state) <> 'object' then
    raise exception 'INVALID_WORKSPACE';
  end if;
  if coalesce((p_state ->> 'version')::integer, 0) <> 1 then
    raise exception 'INVALID_WORKSPACE_VERSION';
  end if;
  if pg_column_size(p_state) > 50 * 1024 * 1024 then
    raise exception 'WORKSPACE_TOO_LARGE';
  end if;

  foreach v_key in array array[
    'members','plans','memberships','payments','products','sales','activities',
    'expenses','inquiries','readNotifications'
  ] loop
    if jsonb_typeof(coalesce(p_state -> v_key, '[]'::jsonb)) <> 'array' then
      raise exception 'INVALID_WORKSPACE_ARRAY:%', v_key;
    end if;
  end loop;

  foreach v_key in array array[
    'members','plans','memberships','payments','products','sales','expenses','inquiries'
  ] loop
    if exists (
      select 1
      from jsonb_array_elements(coalesce(p_state -> v_key, '[]'::jsonb)) item
      group by item ->> 'id'
      having nullif(item ->> 'id', '') is null or count(*) > 1
    ) then
      raise exception 'DUPLICATE_OR_MISSING_ID:%', v_key;
    end if;
  end loop;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_state -> 'memberships', '[]'::jsonb)) membership
    where not exists (
      select 1 from jsonb_array_elements(coalesce(p_state -> 'members', '[]'::jsonb)) member
      where member ->> 'id' = membership ->> 'memberId'
    )
    or not exists (
      select 1 from jsonb_array_elements(coalesce(p_state -> 'plans', '[]'::jsonb)) plan
      where plan ->> 'id' = membership ->> 'planId'
    )
    or coalesce((membership ->> 'price')::numeric, -1) < 0
    or coalesce((membership ->> 'discount')::numeric, -1) < 0
    or coalesce((membership ->> 'joiningFee')::numeric, 0) < 0
    or coalesce((membership ->> 'discount')::numeric, 0) > coalesce((membership ->> 'price')::numeric, 0)
    or (membership ->> 'endDate')::timestamptz < (membership ->> 'startDate')::timestamptz
  ) then
    raise exception 'INVALID_MEMBERSHIP_DATA';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_state -> 'payments', '[]'::jsonb)) payment
    where coalesce((payment ->> 'amount')::numeric, 0) <= 0
      or coalesce((payment ->> 'amount')::numeric, 0) > 1000000000000
      or (
        nullif(payment ->> 'memberId', '') is not null
        and not exists (
          select 1 from jsonb_array_elements(coalesce(p_state -> 'members', '[]'::jsonb)) member
          where member ->> 'id' = payment ->> 'memberId'
        )
      )
      or (
        nullif(payment ->> 'membershipId', '') is not null
        and not exists (
          select 1 from jsonb_array_elements(coalesce(p_state -> 'memberships', '[]'::jsonb)) membership
          where membership ->> 'id' = payment ->> 'membershipId'
        )
      )
      or (
        nullif(payment ->> 'saleId', '') is not null
        and not exists (
          select 1 from jsonb_array_elements(coalesce(p_state -> 'sales', '[]'::jsonb)) sale
          where sale ->> 'id' = payment ->> 'saleId'
        )
      )
  ) then
    raise exception 'INVALID_PAYMENT_DATA';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_state -> 'products', '[]'::jsonb)) product
    where coalesce((product ->> 'price')::numeric, -1) < 0
      or coalesce((product ->> 'cost')::numeric, -1) < 0
      or coalesce((product ->> 'stock')::numeric, -1) < 0
      or coalesce((product ->> 'stock')::numeric, 0) <> trunc(coalesce((product ->> 'stock')::numeric, 0))
  ) then
    raise exception 'INVALID_PRODUCT_DATA';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_state -> 'sales', '[]'::jsonb)) sale
    where coalesce((sale ->> 'qty')::numeric, 0) <= 0
      or coalesce((sale ->> 'qty')::numeric, 0) <> trunc(coalesce((sale ->> 'qty')::numeric, 0))
      or coalesce((sale ->> 'unitPrice')::numeric, -1) < 0
      or coalesce((sale ->> 'unitCost')::numeric, -1) < 0
      or coalesce((sale ->> 'discount')::numeric, -1) < 0
      or coalesce((sale ->> 'total')::numeric, -1) < 0
      or coalesce((sale ->> 'paid')::numeric, 0) < 0
      or coalesce((sale ->> 'paid')::numeric, 0) > coalesce((sale ->> 'total')::numeric, 0)
  ) then
    raise exception 'INVALID_SALE_DATA';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_state -> 'expenses', '[]'::jsonb)) expense
    where coalesce((expense ->> 'amount')::numeric, 0) <= 0
      or coalesce((expense ->> 'amount')::numeric, 0) > 1000000000000
  ) then
    raise exception 'INVALID_EXPENSE_DATA';
  end if;

  if coalesce((p_state ->> 'invoiceSeq')::numeric, -1) < 0
     or coalesce((p_state ->> 'invoiceSeq')::numeric, 0) <> trunc(coalesce((p_state ->> 'invoiceSeq')::numeric, 0)) then
    raise exception 'INVALID_INVOICE_SEQUENCE';
  end if;
end;
$$;

create or replace function public.iv_validate_workspace_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.iv_validate_workspace(new.state);
  return new;
end;
$$;

drop trigger if exists validate_gym_workspace on public.gym_workspaces;
create trigger validate_gym_workspace
before insert or update of state on public.gym_workspaces
for each row execute function public.iv_validate_workspace_trigger();

create or replace function public.get_current_gym_context()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_membership public.gym_users%rowtype;
  v_gym public.gyms%rowtype;
begin
  if v_user is null then
    return null;
  end if;

  select * into v_membership
  from public.gym_users
  where user_id = v_user
  limit 1;
  if not found then
    return null;
  end if;

  select * into v_gym from public.gyms where id = v_membership.gym_id;
  return jsonb_build_object(
    'gym_id', v_membership.gym_id,
    'role', v_membership.role,
    'permissions', coalesce(v_membership.permissions, '{}'::jsonb),
    'display_name', v_membership.display_name,
    'email', v_membership.email,
    'enabled', v_membership.enabled,
    'gym_name', v_gym.name
  );
end;
$$;

create or replace function public.ensure_owner_gym(p_name text, p_initial_state jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_gym_id uuid;
  v_existing_role text;
  v_name text := left(coalesce(nullif(trim(p_name), ''), 'My Gym'), 120);
  v_display_name text := left(coalesce(nullif(trim(p_initial_state -> 'settings' ->> 'adminName'), ''), 'Gym Owner'), 120);
  v_email text := left(coalesce(nullif(trim(p_initial_state -> 'settings' ->> 'email'), ''), ''), 320);
  v_state jsonb;
begin
  if v_user is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select gym_id, role into v_gym_id, v_existing_role
  from public.gym_users
  where user_id = v_user
  limit 1;
  if found then
    return public.get_current_gym_context();
  end if;

  insert into public.gyms (owner_user_id, name)
  values (v_user, v_name)
  on conflict (owner_user_id) do update set updated_at = now()
  returning id into v_gym_id;

  insert into public.gym_users (gym_id, user_id, role, display_name, email, enabled, permissions)
  values (v_gym_id, v_user, 'owner', v_display_name, v_email, true, '{}'::jsonb)
  on conflict (gym_id, user_id) do update set
    role = 'owner', enabled = true, display_name = excluded.display_name,
    email = excluded.email, updated_at = now();

  v_state := coalesce(p_initial_state, '{}'::jsonb) - 'auth' - 'staff';
  v_state := jsonb_set(v_state, '{auth}', '{"email":"","passwordHash":""}'::jsonb, true);
  v_state := jsonb_set(v_state, '{staff}', '{}'::jsonb, true);

  insert into public.gym_workspaces (owner_id, gym_id, state, revision)
  values (v_user, v_gym_id, v_state, 1)
  on conflict (gym_id) do nothing;

  insert into public.audit_logs (gym_id, user_id, role, action, entity_type, entity_id)
  values (v_gym_id, v_user, 'owner', 'gym_created', 'gym', v_gym_id::text);

  return public.get_current_gym_context();
end;
$$;

create or replace function public.load_current_gym_workspace()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_membership public.gym_users%rowtype;
  v_workspace public.gym_workspaces%rowtype;
  v_state jsonb;
  v_products jsonb;
  v_sales jsonb;
  v_can_members boolean;
  v_can_memberships boolean;
  v_can_payments boolean;
  v_can_products boolean;
  v_can_reports boolean;
  v_can_notifications boolean;
  v_can_dashboard boolean;
begin
  if v_user is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select * into v_membership
  from public.gym_users
  where user_id = v_user
  limit 1;
  if not found then
    return null;
  end if;
  if not v_membership.enabled then
    raise exception 'STAFF_DISABLED';
  end if;

  select * into v_workspace
  from public.gym_workspaces
  where gym_id = v_membership.gym_id;
  if not found then
    return null;
  end if;

  v_state := coalesce(v_workspace.state, '{}'::jsonb) - 'auth' - 'staff';
  v_state := jsonb_set(v_state, '{auth}', '{"email":"","passwordHash":""}'::jsonb, true);
  v_state := jsonb_set(v_state, '{staff}', '{}'::jsonb, true);

  if v_membership.role = 'receptionist' then
    v_can_members := public.iv_has_permission(v_membership.permissions, 'members');
    v_can_memberships := public.iv_has_permission(v_membership.permissions, 'memberships');
    v_can_payments := public.iv_has_permission(v_membership.permissions, 'payments');
    v_can_products := public.iv_has_permission(v_membership.permissions, 'products');
    v_can_reports := public.iv_has_permission(v_membership.permissions, 'reports');
    v_can_notifications := public.iv_has_permission(v_membership.permissions, 'notifications');
    v_can_dashboard := public.iv_has_permission(v_membership.permissions, 'dashboard');

    if not (v_can_members or v_can_memberships or v_can_payments or v_can_products or v_can_reports or v_can_notifications) then
      v_state := jsonb_set(v_state, '{members}', '[]'::jsonb, true);
    end if;
    if not (v_can_memberships or v_can_payments or v_can_reports or v_can_notifications) then
      v_state := jsonb_set(v_state, '{memberships}', '[]'::jsonb, true);
      v_state := jsonb_set(v_state, '{plans}', '[]'::jsonb, true);
    end if;
    if not (v_can_payments or v_can_reports or v_can_notifications or (v_can_dashboard and public.iv_has_permission(v_membership.permissions, 'viewRevenue'))) then
      v_state := jsonb_set(v_state, '{payments}', '[]'::jsonb, true);
    end if;
    if not (v_can_products or v_can_reports or v_can_notifications) then
      v_state := jsonb_set(v_state, '{products}', '[]'::jsonb, true);
    end if;
    if not (v_can_products or v_can_payments or v_can_reports or (v_can_dashboard and public.iv_has_permission(v_membership.permissions, 'viewRevenue'))) then
      v_state := jsonb_set(v_state, '{sales}', '[]'::jsonb, true);
    end if;
    if not (public.iv_has_permission(v_membership.permissions, 'expenses') or v_can_reports) then
      v_state := jsonb_set(v_state, '{expenses}', '[]'::jsonb, true);
    end if;
    if not (public.iv_has_permission(v_membership.permissions, 'inquiries') or v_can_notifications) then
      v_state := jsonb_set(v_state, '{inquiries}', '[]'::jsonb, true);
    end if;
    if not v_can_notifications then
      v_state := jsonb_set(v_state, '{readNotifications}', '[]'::jsonb, true);
    end if;
    if not (v_can_dashboard or v_can_notifications) then
      v_state := jsonb_set(v_state, '{activities}', '[]'::jsonb, true);
    end if;

    -- Product costs and historical cost-of-goods are owner-sensitive unless
    -- the owner explicitly grants the cost/profit permission.
    if not public.iv_has_permission(v_membership.permissions, 'viewProductCost') then
      select coalesce(jsonb_agg(jsonb_set(item, '{cost}', '0'::jsonb, true)), '[]'::jsonb)
      into v_products
      from jsonb_array_elements(coalesce(v_state -> 'products', '[]'::jsonb)) item;
      select coalesce(jsonb_agg(jsonb_set(item, '{unitCost}', '0'::jsonb, true)), '[]'::jsonb)
      into v_sales
      from jsonb_array_elements(coalesce(v_state -> 'sales', '[]'::jsonb)) item;
      v_state := jsonb_set(v_state, '{products}', coalesce(v_products, '[]'::jsonb), true);
      v_state := jsonb_set(v_state, '{sales}', coalesce(v_sales, '[]'::jsonb), true);
    end if;

    -- Staff never need owner account identity fields from workspace settings.
    v_state := jsonb_set(
      v_state,
      '{settings,adminName}',
      to_jsonb('Gym Owner'::text),
      true
    );
  end if;

  return jsonb_build_object(
    'gym_id', v_membership.gym_id,
    'role', v_membership.role,
    'permissions', coalesce(v_membership.permissions, '{}'::jsonb),
    'display_name', v_membership.display_name,
    'email', v_membership.email,
    'revision', v_workspace.revision,
    'state', v_state
  );
end;
$$;

create or replace function public.save_current_gym_workspace(p_state jsonb, p_expected_revision bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_membership public.gym_users%rowtype;
  v_workspace public.gym_workspaces%rowtype;
  v_next jsonb;
  v_products jsonb;
  v_sales jsonb;
  v_invoice_seq bigint;
  v_changed_keys jsonb;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_state is null or jsonb_typeof(p_state) <> 'object' then raise exception 'INVALID_WORKSPACE'; end if;

  select * into v_membership
  from public.gym_users
  where user_id = v_user
  limit 1;
  if not found then raise exception 'GYM_MEMBERSHIP_REQUIRED'; end if;
  if not v_membership.enabled then raise exception 'STAFF_DISABLED'; end if;

  select * into v_workspace
  from public.gym_workspaces
  where gym_id = v_membership.gym_id
  for update;
  if not found then raise exception 'WORKSPACE_NOT_FOUND'; end if;

  if p_expected_revision is null or p_expected_revision <> v_workspace.revision then
    raise exception 'WORKSPACE_CONFLICT';
  end if;

  if v_membership.role = 'owner' then
    v_next := p_state - 'auth' - 'staff';
    v_next := jsonb_set(v_next, '{auth}', '{"email":"","passwordHash":""}'::jsonb, true);
    v_next := jsonb_set(v_next, '{staff}', '{}'::jsonb, true);
  else
    -- Start from the authoritative server state and only replace areas the
    -- owner explicitly delegated. This prevents client-side privilege bypasses
    -- and prevents hidden fields from being zeroed by a filtered client copy.
    v_next := v_workspace.state;

    if public.iv_has_permission(v_membership.permissions, 'members') then
      v_next := jsonb_set(v_next, '{members}', coalesce(p_state -> 'members', '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'memberships') then
      v_next := jsonb_set(v_next, '{memberships}', coalesce(p_state -> 'memberships', '[]'::jsonb), true);
      v_next := jsonb_set(v_next, '{plans}', coalesce(p_state -> 'plans', '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'payments') then
      -- Receptionists may record new payments but cannot rewrite or remove
      -- financial history by crafting a workspace payload outside the UI.
      if exists (
        select 1
        from jsonb_array_elements(coalesce(v_workspace.state -> 'payments', '[]'::jsonb)) original
        where not exists (
          select 1
          from jsonb_array_elements(coalesce(p_state -> 'payments', '[]'::jsonb)) incoming
          where incoming ->> 'id' = original ->> 'id' and incoming = original
        )
      ) then
        raise exception 'PAYMENT_HISTORY_IMMUTABLE';
      end if;
      v_next := jsonb_set(v_next, '{payments}', coalesce(p_state -> 'payments', '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'products') then
      v_products := coalesce(p_state -> 'products', '[]'::jsonb);
      v_sales := coalesce(p_state -> 'sales', '[]'::jsonb);

      -- Existing sales are accounting history. Product permission allows new
      -- sales and inventory changes, not retroactive sale edits/deletes.
      if exists (
        select 1
        from jsonb_array_elements(coalesce(v_workspace.state -> 'sales', '[]'::jsonb)) original
        where not exists (
          select 1
          from jsonb_array_elements(v_sales) incoming
          where incoming ->> 'id' = original ->> 'id' and incoming = original
        )
      ) then
        raise exception 'SALE_HISTORY_IMMUTABLE';
      end if;

      if not public.iv_has_permission(v_membership.permissions, 'viewProductCost') then
        select coalesce(jsonb_agg(
          jsonb_set(
            incoming,
            '{cost}',
            coalesce(
              (select original -> 'cost'
               from jsonb_array_elements(coalesce(v_workspace.state -> 'products', '[]'::jsonb)) original
               where original ->> 'id' = incoming ->> 'id'
               limit 1),
              '0'::jsonb
            ),
            true
          )
        ), '[]'::jsonb)
        into v_products
        from jsonb_array_elements(v_products) incoming;

        select coalesce(jsonb_agg(
          jsonb_set(
            incoming,
            '{unitCost}',
            coalesce(
              (select original -> 'unitCost'
               from jsonb_array_elements(coalesce(v_workspace.state -> 'sales', '[]'::jsonb)) original
               where original ->> 'id' = incoming ->> 'id'
               limit 1),
              (select product -> 'cost'
               from jsonb_array_elements(coalesce(v_workspace.state -> 'products', '[]'::jsonb)) product
               where product ->> 'id' = incoming ->> 'productId'
               limit 1),
              '0'::jsonb
            ),
            true
          )
        ), '[]'::jsonb)
        into v_sales
        from jsonb_array_elements(v_sales) incoming;
      end if;

      v_next := jsonb_set(v_next, '{products}', coalesce(v_products, '[]'::jsonb), true);
      v_next := jsonb_set(v_next, '{sales}', coalesce(v_sales, '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'expenses') then
      v_next := jsonb_set(v_next, '{expenses}', coalesce(p_state -> 'expenses', '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'inquiries') then
      v_next := jsonb_set(v_next, '{inquiries}', coalesce(p_state -> 'inquiries', '[]'::jsonb), true);
    end if;
    if public.iv_has_permission(v_membership.permissions, 'notifications') then
      v_next := jsonb_set(v_next, '{readNotifications}', coalesce(p_state -> 'readNotifications', '[]'::jsonb), true);
    end if;

    if public.iv_has_permission(v_membership.permissions, 'members')
       or public.iv_has_permission(v_membership.permissions, 'memberships')
       or public.iv_has_permission(v_membership.permissions, 'payments')
       or public.iv_has_permission(v_membership.permissions, 'products')
       or public.iv_has_permission(v_membership.permissions, 'expenses')
       or public.iv_has_permission(v_membership.permissions, 'inquiries') then
      v_next := jsonb_set(v_next, '{activities}', coalesce(p_state -> 'activities', '[]'::jsonb), true);
    end if;

    -- Invoice numbers are shared by payments and product sales. They may only
    -- move forward and only by users allowed to create those records.
    if public.iv_has_permission(v_membership.permissions, 'payments')
       or public.iv_has_permission(v_membership.permissions, 'products') then
      v_invoice_seq := greatest(
        coalesce((v_workspace.state ->> 'invoiceSeq')::bigint, 0),
        coalesce((p_state ->> 'invoiceSeq')::bigint, 0)
      );
      v_next := jsonb_set(v_next, '{invoiceSeq}', to_jsonb(v_invoice_seq), true);
    end if;

    v_next := v_next - 'auth' - 'staff';
    v_next := jsonb_set(v_next, '{auth}', '{"email":"","passwordHash":""}'::jsonb, true);
    v_next := jsonb_set(v_next, '{staff}', '{}'::jsonb, true);
  end if;

  select coalesce(jsonb_agg(changed.key), '[]'::jsonb)
  into v_changed_keys
  from (
    select entry.key
    from jsonb_object_keys(v_next) as entry(key)
    where (v_workspace.state -> entry.key) is distinct from (v_next -> entry.key)
  ) changed;

  update public.gym_workspaces
  set state = v_next,
      revision = revision + 1,
      updated_at = now()
  where id = v_workspace.id
  returning revision into v_workspace.revision;

  update public.gyms
  set name = coalesce(nullif(trim(v_next -> 'settings' ->> 'gymName'), ''), name),
      updated_at = now()
  where id = v_membership.gym_id
    and v_membership.role = 'owner';

  insert into public.audit_logs (gym_id, user_id, role, action, entity_type, entity_id, metadata)
  values (
    v_membership.gym_id,
    v_user,
    v_membership.role,
    'workspace_updated',
    'workspace',
    v_workspace.id::text,
    jsonb_build_object('changed_keys', v_changed_keys, 'revision', v_workspace.revision)
  );

  return jsonb_build_object('revision', v_workspace.revision, 'updated_at', now());
end;
$$;

create or replace function public.record_audit_event(
  p_action text,
  p_entity_type text default null,
  p_entity_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membership public.gym_users%rowtype;
begin
  select * into v_membership from public.gym_users where user_id = auth.uid() and enabled limit 1;
  if not found then raise exception 'GYM_MEMBERSHIP_REQUIRED'; end if;
  if p_action not in (
    'login', 'logout', 'settings_updated', 'backup_restored', 'staff_updated',
    'member_created', 'member_updated', 'member_deleted', 'payment_created',
    'membership_renewed', 'product_sold', 'expense_created', 'expense_updated',
    'inquiry_updated'
  ) then raise exception 'INVALID_AUDIT_ACTION'; end if;
  insert into public.audit_logs (gym_id, user_id, role, action, entity_type, entity_id, metadata)
  values (
    v_membership.gym_id,
    auth.uid(),
    v_membership.role,
    p_action,
    left(p_entity_type, 80),
    left(p_entity_id, 160),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.consume_api_rate_limit(
  p_scope text,
  p_subject text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.api_rate_limits%rowtype;
  v_now timestamptz := now();
  v_window interval;
begin
  if p_limit < 1 or p_limit > 10000 or p_window_seconds < 1 or p_window_seconds > 86400 then
    return false;
  end if;
  v_window := make_interval(secs => p_window_seconds);

  insert into public.api_rate_limits (scope, subject, window_started_at, request_count, updated_at)
  values (left(p_scope, 120), left(p_subject, 200), v_now, 1, v_now)
  on conflict (scope, subject) do update set
    window_started_at = case
      when public.api_rate_limits.window_started_at + v_window <= v_now then v_now
      else public.api_rate_limits.window_started_at
    end,
    request_count = case
      when public.api_rate_limits.window_started_at + v_window <= v_now then 1
      else public.api_rate_limits.request_count + 1
    end,
    updated_at = v_now
  returning * into v_row;

  return v_row.request_count <= p_limit;
end;
$$;

revoke all on function public.consume_api_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.get_current_gym_context() to authenticated;
grant execute on function public.ensure_owner_gym(text, jsonb) to authenticated;
grant execute on function public.load_current_gym_workspace() to authenticated;
grant execute on function public.save_current_gym_workspace(jsonb, bigint) to authenticated;
grant execute on function public.record_audit_event(text, text, text, jsonb) to authenticated;

-- Billing becomes tenant-scoped as well. owner_id is retained for provider
-- compatibility/backfill, but authorization and limits use gym_id.
alter table public.subscription_entitlements
  add column if not exists gym_id uuid references public.gyms(id) on delete cascade;

update public.subscription_entitlements entitlement
set gym_id = gym.id
from public.gyms gym
where entitlement.gym_id is null
  and gym.owner_user_id = entitlement.owner_id;

create unique index if not exists subscription_entitlements_gym_idx
  on public.subscription_entitlements (gym_id)
  where gym_id is not null;

drop policy if exists "Owners can read their own subscription" on public.subscription_entitlements;
create policy "Owners can read their gym subscription"
  on public.subscription_entitlements for select to authenticated
  using (gym_id = public.iv_current_gym_id() and public.iv_is_current_gym_owner());

create or replace function public.redeem_recharge_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner uuid := auth.uid();
  v_gym uuid := public.iv_current_gym_id();
  v_hash text;
  v_code public.recharge_codes%rowtype;
  v_current public.subscription_entitlements%rowtype;
  v_base timestamptz;
  v_end timestamptz;
begin
  if v_owner is null or v_gym is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.iv_is_current_gym_owner() then raise exception 'OWNER_REQUIRED'; end if;
  if p_code is null or length(trim(p_code)) < 8 then raise exception 'INVALID_RECHARGE_CODE'; end if;

  v_hash := encode(digest(upper(trim(p_code)), 'sha256'), 'hex');
  select * into v_code from public.recharge_codes where code_hash = v_hash for update;
  if not found then raise exception 'INVALID_RECHARGE_CODE'; end if;
  if v_code.valid_until is not null and v_code.valid_until < now() then raise exception 'RECHARGE_CODE_EXPIRED'; end if;

  if v_code.redeemed_at is not null then
    if v_code.redeemed_by = v_owner then
      select * into v_current from public.subscription_entitlements where gym_id = v_gym;
      return jsonb_build_object(
        'status', coalesce(v_current.status, 'free'),
        'source', v_current.source,
        'current_period_end', v_current.current_period_end,
        'already_redeemed', true
      );
    end if;
    raise exception 'RECHARGE_CODE_ALREADY_USED';
  end if;

  select * into v_current from public.subscription_entitlements where gym_id = v_gym for update;
  v_base := greatest(
    now(),
    coalesce(v_current.recharge_period_end, now()),
    coalesce(v_current.provider_period_end, now())
  );
  v_end := v_base + make_interval(days => v_code.duration_days);

  insert into public.subscription_entitlements (
    owner_id, gym_id, status, source, recharge_period_end, current_period_end, last_verified_at, updated_at
  ) values (
    v_owner, v_gym, 'active', 'recharge', v_end, v_end, now(), now()
  ) on conflict (owner_id) do update set
    gym_id = excluded.gym_id,
    recharge_period_end = excluded.recharge_period_end,
    last_verified_at = now(),
    updated_at = now();

  update public.recharge_codes set redeemed_by = v_owner, redeemed_at = now() where id = v_code.id;
  insert into public.audit_logs (gym_id, user_id, role, action, entity_type, entity_id, metadata)
  values (v_gym, v_owner, 'owner', 'subscription_recharged', 'subscription', v_gym::text,
    jsonb_build_object('days_added', v_code.duration_days));

  return jsonb_build_object(
    'status', 'active', 'source', 'recharge', 'current_period_end', v_end,
    'days_added', v_code.duration_days, 'already_redeemed', false
  );
end;
$$;

revoke all on function public.redeem_recharge_code(text) from public, anon;
grant execute on function public.redeem_recharge_code(text) to authenticated;

create or replace function public.enforce_gym_member_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member_count integer := 0;
  v_old_member_count integer := 0;
  v_paid boolean := false;
begin
  select count(*) into v_member_count
  from jsonb_array_elements(coalesce(new.state -> 'members', '[]'::jsonb)) as member
  where coalesce(member ->> 'type', 'member') <> 'walk_in'
    and nullif(member ->> 'deletedAt', '') is null;

  if tg_op = 'UPDATE' then
    select count(*) into v_old_member_count
    from jsonb_array_elements(coalesce(old.state -> 'members', '[]'::jsonb)) as member
    where coalesce(member ->> 'type', 'member') <> 'walk_in'
      and nullif(member ->> 'deletedAt', '') is null;
  end if;

  if v_member_count <= 10 or v_member_count <= v_old_member_count then return new; end if;

  select exists (
    select 1 from public.subscription_entitlements entitlement
    where entitlement.gym_id = new.gym_id
      and entitlement.status = 'active'
      and entitlement.current_period_end > now()
  ) into v_paid;

  if not v_paid then raise exception 'SUBSCRIPTION_REQUIRED_MEMBER_LIMIT'; end if;
  return new;
end;
$$;

drop trigger if exists set_gyms_updated_at on public.gyms;
create trigger set_gyms_updated_at before update on public.gyms
for each row execute function public.set_updated_at();

drop trigger if exists set_gym_users_updated_at on public.gym_users;
create trigger set_gym_users_updated_at before update on public.gym_users
for each row execute function public.set_updated_at();
